import { BadgeCheck, CircleDot, Clock3, Route as RouteIcon, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import StatusBadge from '../../components/StatusBadge'
import { statusLabel } from '../../domain/workflowEngine.js'
import { useWorkspace } from '../../state/WorkspaceContext'

export default function TraceCenter() {
  const { workspace } = useWorkspace()
  const [selectedId, setSelectedId] = useState(workspace.requests[0]?.id ?? '')
  const [query, setQuery] = useState('')
  const requests = workspace.requests.filter((item) => `${item.title}${item.requestNo}`.toLowerCase().includes(query.toLowerCase()))
  const selected = workspace.requests.find((item) => item.id === selectedId) ?? requests[0]
  const events = useMemo(() => workspace.audit.filter((event) => event.requestId === selected?.id).sort((a, b) => a.createdAt.localeCompare(b.createdAt)), [workspace.audit, selected?.id])
  return <div className="page-shell max-w-[1500px]"><div className="mb-6"><div className="eyebrow">Process Instances</div><h2 className="page-title mt-2">流程轨迹</h2><p className="page-subtitle">查看每个流程实例的节点、处理人、意见与状态变化。</p></div><div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><section className="app-card overflow-hidden"><div className="panel-header"><div><h3 className="section-title">流程实例</h3><p className="mt-1 text-xs text-secondary-500">{requests.length} 条记录</p></div></div><div className="relative mx-3 mt-3"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-secondary-400" /><input className="field pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索申请单" /></div><div className="max-h-[580px] space-y-2 overflow-auto p-3">{requests.map((request) => <button key={request.id} onClick={() => setSelectedId(request.id)} className={`w-full rounded-xl border p-4 text-left transition ${selected?.id === request.id ? 'border-primary-300 bg-primary-50' : 'border-secondary-100 hover:bg-secondary-50'}`}><div className="flex items-center justify-between gap-3"><strong className="truncate text-sm text-secondary-900">{request.title}</strong><StatusBadge status={request.status} /></div><div className="mt-2 flex items-center text-xs text-secondary-400"><span className="font-mono">{request.requestNo}</span><span className="mx-2">·</span><span>¥ {request.amount.toLocaleString()}</span></div></button>)}</div></section>
    {selected ? <section className="app-card overflow-hidden"><div className="panel-header"><div className="min-w-0"><div className="flex items-center gap-2"><RouteIcon size={18} className="shrink-0 text-primary-600" /><h3 className="truncate section-title">{selected.title}</h3></div><p className="mt-1 font-mono text-xs text-secondary-400">{selected.requestNo}</p></div><StatusBadge status={selected.status} /></div><div className="grid gap-3 border-b border-secondary-100 bg-secondary-50 p-5 sm:grid-cols-3"><div><small className="text-secondary-400">申请人</small><div className="mt-1 text-sm font-medium">{selected.applicant}</div></div><div><small className="text-secondary-400">申请金额</small><div className="mt-1 text-sm font-medium">¥ {selected.amount.toLocaleString()}</div></div><div><small className="text-secondary-400">当前状态</small><div className="mt-1 text-sm font-medium">{statusLabel(selected.status)}</div></div></div><div className="p-5 sm:p-7"><div className="relative ml-4 border-l-2 border-secondary-200 pl-8">{events.map((event, index) => <div key={event.id} className="relative pb-8 last:pb-2"><span className={`absolute -left-[45px] top-0 grid h-7 w-7 place-items-center rounded-full ring-4 ring-white ${index === events.length - 1 ? 'bg-primary-600 text-white' : 'bg-accent-100 text-accent-700'}`}>{index === events.length - 1 ? <CircleDot size={13} /> : <BadgeCheck size={14} />}</span><div className="rounded-2xl border border-secondary-200 p-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-secondary-900">{event.action}</strong><span className="badge-gray">{event.actor}</span><span className="ml-auto flex items-center gap-1 text-[11px] text-secondary-400"><Clock3 size={12} />{new Date(event.createdAt).toLocaleString()}</span></div><p className="mt-2 text-sm leading-6 text-secondary-600">{event.detail}</p></div></div>)}<div className="relative"><span className="absolute -left-[45px] top-0 grid h-7 w-7 place-items-center rounded-full bg-secondary-100 text-secondary-400 ring-4 ring-white"><CircleDot size={13} /></span><div className="rounded-2xl border border-dashed border-secondary-300 bg-secondary-50 p-4 text-sm text-secondary-500">流程当前状态：{statusLabel(selected.status)}</div></div></div></div></section> : <div className="empty-state app-card"><RouteIcon size={30} className="text-secondary-300" /><p className="mt-3 text-sm text-secondary-500">选择一条流程实例</p></div>}
  </div></div>
}
