import { AppWindow, ArrowRight, Boxes, CalendarDays, Copy, LayoutTemplate, LoaderCircle, LogOut, Plus, Sparkles, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import ConfirmDialog from '../../components/ConfirmDialog'
import PageHeader from '../../components/PageHeader'
import { usePlatform } from '../../state/PlatformContext'
import type { AppTemplate } from '../../types/platform'
import { withMinimumLoading } from '../../utils/async'

export default function AppManager({ standalone = false }: { standalone?: boolean }) {
  const { currentUser, userApps, activeApp, setActiveApp, createApp, deleteApp, logout } = usePlatform()
  const navigate = useNavigate()
  const [showCreate, setShowCreate] = useState(false)
  const [creating, setCreating] = useState(false)
  const [deletingId, setDeletingId] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; name: string } | null>(null)
  const [logoutOpen, setLogoutOpen] = useState(false)
  const [loggingOut, setLoggingOut] = useState(false)
  const [form, setForm] = useState({ name: '', description: '', template: 'procurement' as AppTemplate })

  const openApp = async (id: string) => { await setActiveApp(id); navigate('/studio/overview') }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (creating) return; setCreating(true); try { await withMinimumLoading(() => createApp(form.name, form.description, form.template)); setShowCreate(false); setForm({ name: '', description: '', template: 'procurement' }); navigate('/studio/overview') } finally { setCreating(false) } }
  const removeApp = (id: string, name: string) => setDeleteTarget({ id, name })
  const confirmRemoveApp = async () => { if (!deleteTarget) return; setDeletingId(deleteTarget.id); try { await withMinimumLoading(() => deleteApp(deleteTarget.id)); setDeleteTarget(null) } finally { setDeletingId('') } }
  const confirmLogout = async () => { if (loggingOut) return; setLoggingOut(true); try { await withMinimumLoading(logout) } finally { setLoggingOut(false) } }

  const content = <div className="page-shell max-w-[1500px]">
    <PageHeader eyebrow="Application Center" title="我的应用" description="创建和管理彼此独立的低代码应用。每个应用拥有自己的模型、页面、流程、版本和运行数据。" actions={<button className="btn-primary" onClick={() => setShowCreate(true)}><Plus size={17} />新建应用</button>} />
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
      {userApps.map((app, index) => <article key={app.id} className="app-card group overflow-hidden transition hover:-translate-y-1 hover:border-primary-200 hover:shadow-float"><button className="w-full p-5 text-left" disabled={deletingId === app.id} onClick={() => openApp(app.id)}><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${index % 3 === 0 ? 'bg-primary-50 text-primary-700' : index % 3 === 1 ? 'bg-cyan-50 text-cyan-700' : 'bg-accent-50 text-accent-700'}`}><AppWindow size={22} /></span><span className={app.status === 'published' ? 'badge-green' : 'badge-amber'}>{app.status === 'published' ? '已发布' : '开发中'}</span></div><h2 className="mt-5 text-lg font-semibold text-secondary-900">{app.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-secondary-500">{app.description || '还没有应用说明'}</p><div className="mt-5 flex items-center gap-2 text-xs text-secondary-400"><CalendarDays size={14} />更新于 {new Date(app.updatedAt).toLocaleDateString()}<ArrowRight size={16} className="ml-auto transition group-hover:translate-x-1 group-hover:text-primary-600" /></div></button><div className="flex items-center justify-between border-t border-secondary-100 bg-secondary-50 px-4 py-3"><span className="flex items-center gap-1.5 text-[11px] text-secondary-400"><LayoutTemplate size={13} />{app.template === 'procurement' ? '采购协同模板' : '空白应用'}</span><button className="rounded-lg p-2 text-secondary-400 hover:bg-red-50 hover:text-red-600 disabled:cursor-wait disabled:opacity-60" disabled={Boolean(deletingId)} onClick={() => removeApp(app.id, app.name)} aria-label={`删除应用 ${app.name}`} aria-busy={deletingId === app.id}>{deletingId === app.id ? <LoaderCircle size={15} className="animate-spin" /> : <Trash2 size={15} />}</button></div></article>)}
      <button onClick={() => setShowCreate(true)} className="flex min-h-64 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-secondary-200 bg-white text-center transition hover:border-primary-300 hover:bg-primary-50"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-secondary-100 text-secondary-500"><Plus size={22} /></span><strong className="mt-4 text-sm text-secondary-800">创建新应用</strong><span className="mt-1 text-xs text-secondary-400">从模板或空白开始</span></button>
    </div>
    {!userApps.length && <div className="mt-5 rounded-2xl border border-primary-100 bg-primary-50 p-4 text-sm text-primary-800">当前账号还没有应用，点击“新建应用”开始搭建。</div>}
  </div>

  return <>{standalone ? <div className="min-h-screen bg-secondary-50"><header className="flex h-16 items-center justify-between border-b border-secondary-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary-600 text-white"><Boxes size={18} /></span><div><strong className="block text-sm">Forge Studio</strong><span className="text-[11px] text-secondary-400">你好，{currentUser?.name}</span></div></div><button className="btn-ghost" onClick={() => setLogoutOpen(true)}><LogOut size={16} />退出登录</button></header>{content}</div> : content}
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-secondary-900/40 p-4 backdrop-blur-sm"><form onSubmit={submit} className="app-card w-full max-w-xl animate-slide-up overflow-hidden"><div className="panel-header"><div><div className="flex items-center gap-2"><Sparkles size={18} className="text-primary-600" /><h2 className="section-title">新建低代码应用</h2></div><p className="mt-1 text-xs text-secondary-500">选择起点，稍后可自由调整所有配置</p></div><button type="button" className="rounded-lg p-2 text-secondary-400 hover:bg-secondary-100" onClick={() => setShowCreate(false)} aria-label="关闭新建应用"><X size={18} /></button></div><div className="space-y-5 p-5"><label><span className="field-label">应用名称 *</span><input required className="field" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：客户工单中心" /></label><label><span className="field-label">应用说明</span><textarea className="field min-h-20" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="简要说明应用解决的问题" /></label><div><span className="field-label">创建方式</span><div className="grid gap-3 sm:grid-cols-2">{[{ value: 'procurement', label: '采购协同模板', description: '带完整模型、页面与审批流程', icon: Copy }, { value: 'blank', label: '空白应用', description: '从第一个数据对象开始搭建', icon: Boxes }].map((option) => <button key={option.value} type="button" onClick={() => setForm({ ...form, template: option.value as AppTemplate })} className={`rounded-2xl border p-4 text-left transition ${form.template === option.value ? 'border-primary-400 bg-primary-50 ring-2 ring-primary-100' : 'border-secondary-200 hover:border-primary-200'}`}><option.icon size={20} className={form.template === option.value ? 'text-primary-600' : 'text-secondary-400'} /><strong className="mt-3 block text-sm text-secondary-900">{option.label}</strong><span className="mt-1 block text-xs leading-5 text-secondary-500">{option.description}</span></button>)}</div></div></div><div className="flex justify-end gap-3 border-t border-secondary-100 bg-secondary-50 p-4"><button type="button" className="btn-secondary" onClick={() => setShowCreate(false)}>取消</button><button className="btn-primary"><Plus size={16} />创建并打开</button></div></form></div>}
    <ConfirmDialog open={deleteTarget !== null} title="删除应用" description={`确定删除「${deleteTarget?.name ?? ''}」吗？该应用的配置、发布版本和运行数据都会从本机移除。`} busy={Boolean(deletingId)} onCancel={() => setDeleteTarget(null)} onConfirm={confirmRemoveApp} />
    <ConfirmDialog open={logoutOpen} title="退出登录" description={`确定退出账号「${currentUser?.name ?? ''}」吗？`} confirmText="确认退出" variant="warning" warningText="退出后将返回登录页面，本机中的应用和配置数据不会被删除。" busy={loggingOut} onCancel={() => setLogoutOpen(false)} onConfirm={confirmLogout} />
    {creating && <div role="status" aria-live="polite" className="fixed inset-0 z-[60] grid place-items-center bg-secondary-900/20 backdrop-blur-[2px]"><div className="flex items-center gap-3 rounded-2xl bg-white px-5 py-4 text-sm font-medium text-secondary-800 shadow-float"><LoaderCircle size={19} className="animate-spin text-primary-600" />正在创建应用…</div></div>}
  </>
}
